### ISSUE TITLE
Sources don't build

### ISSUE THREAD

**Issue by kortov** [jameskleeh/groovy-excel-builder#26]
I think the reason is because the old codenarc pulls the new groovy, I think upgrading codenarc could solve the problem despite the need to update the rules
![Снимок24](https://user-images.githubusercontent.com/6348215/54936234-7cfb0080-4f3b-11e9-8d8a-c8362339c1b8.PNG)

[Here's the link](https://discuss.gradle.org/t/sudden-issue-with-gradle-3-5-1-and-codenarc/30064/3)

```java
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':codenarcMain'.
> java.lang.NoClassDefFoundError: groovy/text/SimpleTemplateEngine
```

**Comment by jameskleeh** [comment]
I've updated codenarc and now it fails for a different reason

**Comment by kortov** [comment]
There are many ways to fix that, I'll push a PR with fixes, may be you'll add some more there, but here are the details:

Codenarc enhanced rules require all the dependencies (for example POI) in the classpath [link](https://github.com/CodeNarc/CodeNarc/issues/306#issuecomment-357814085). Honestly I don't know the way how to give him the classpath so I removed those rules. As I can see, your last successful build logged  [such errors](https://travis-ci.org/jameskleeh/groovy-excel-builder/builds/291882870?utm_source=github_status&utm_medium=notification) 
```java
Compilation failed for [CustomCompilerPhaseSourceDecorator[SourceFile[/home/travis/build/jameskleeh/groovy-excel-builder/src/main/groovy/com/jameskleeh/excel/Column.groovy]]].
```
but it worked in codenarc 0.25.2. You can simply return codenarc to this version with this (I'm not good at gradle, for me it the easiest way to force dependency)
```groovy
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.requested.group == 'org.codehaus.groovy') {
            details.useVersion '2.4.7'
        }
    }
}
```
and build will succed.


But I just removed some unnecessary rules, fixed some errors and added java plugin for easier ide support of the project, please check the PR 

These were codenarc intermediate results 
[codenarc-results.zip](https://github.com/jameskleeh/groovy-excel-builder/files/3006899/codenarc-results.zip)
